//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class employes
    {
        public int id { get; set; }
        public Nullable<int> id_passport { get; set; }
        public Nullable<int> id_health { get; set; }
        public Nullable<int> id_cex { get; set; }
        public Nullable<int> id_requisites { get; set; }
    
        public virtual cex cex { get; set; }
        public virtual health health { get; set; }
        public virtual passport passport { get; set; }
        public virtual requisites requisites { get; set; }
    }
}
