//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor
{
    using System;
    using System.Collections.Generic;
    
    public partial class passport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public passport()
        {
            this.employes = new HashSet<employes>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_familyStatus { get; set; }
        public string sex { get; set; }
        public string passport_series { get; set; }
        public string passport_number { get; set; }
        public string lastname { get; set; }
        public string name { get; set; }
        public string fathername { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employes> employes { get; set; }
        public virtual family_status family_status { get; set; }
    }
}
